/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt --arg-struct-name=athena_args --func-name=arg_parser --no-handle-error

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *athena_args_purpose = "Scenario editor for Ares, Xsera, and eventually Antares.";

const char *athena_args_usage = "Usage: Athena [OPTIONS]...";

const char *athena_args_description = "";

const char *athena_args_full_help[] = {
  "  -h, --help         Print help and exit",
  "      --full-help    Print help, including hidden options, and exit",
  "  -V, --version      Print version and exit",
  "  -b, --base[=FILE]  Use base data.",
  "  -d, --download     Download data",
  "  -c, --check        Preform consistency check",
  "  -l, --list         List file contents",
  "  -t, --type=ENUM    Filetype to output  (possible values=\"ares\", \"xsera\")",
  "  -o, --out=FILE     Output location",
    0
};

static void
init_help_array(void)
{
  athena_args_help[0] = athena_args_full_help[0];
  athena_args_help[1] = athena_args_full_help[1];
  athena_args_help[2] = athena_args_full_help[2];
  athena_args_help[3] = athena_args_full_help[3];
  athena_args_help[4] = athena_args_full_help[4];
  athena_args_help[5] = athena_args_full_help[7];
  athena_args_help[6] = athena_args_full_help[8];
  athena_args_help[7] = 0; 
  
}

const char *athena_args_help[8];

typedef enum {ARG_NO
  , ARG_STRING
  , ARG_ENUM
} arg_parser_arg_type;

static
void clear_given (struct athena_args *args_info);
static
void clear_args (struct athena_args *args_info);

static int
arg_parser_internal (int argc, char **argv, struct athena_args *args_info,
                        struct arg_parser_params *params, const char *additional_error);

static int
arg_parser_required2 (struct athena_args *args_info, const char *prog_name, const char *additional_error);

const char *arg_parser_type_values[] = {"ares", "xsera", 0}; /*< Possible values for type. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct athena_args *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->base_given = 0 ;
  args_info->download_given = 0 ;
  args_info->check_given = 0 ;
  args_info->list_given = 0 ;
  args_info->type_given = 0 ;
  args_info->out_given = 0 ;
}

static
void clear_args (struct athena_args *args_info)
{
  FIX_UNUSED (args_info);
  args_info->base_arg = NULL;
  args_info->base_orig = NULL;
  args_info->type_arg = type__NULL;
  args_info->type_orig = NULL;
  args_info->out_arg = NULL;
  args_info->out_orig = NULL;
  
}

static
void init_args_info(struct athena_args *args_info)
{

  init_help_array(); 
  args_info->help_help = athena_args_full_help[0] ;
  args_info->full_help_help = athena_args_full_help[1] ;
  args_info->version_help = athena_args_full_help[2] ;
  args_info->base_help = athena_args_full_help[3] ;
  args_info->download_help = athena_args_full_help[4] ;
  args_info->check_help = athena_args_full_help[5] ;
  args_info->list_help = athena_args_full_help[6] ;
  args_info->type_help = athena_args_full_help[7] ;
  args_info->out_help = athena_args_full_help[8] ;
  
}

void
arg_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(ARG_PARSER_PACKAGE_NAME) ? ARG_PARSER_PACKAGE_NAME : ARG_PARSER_PACKAGE),
     ARG_PARSER_VERSION);
}

static void print_help_common(void) {
  arg_parser_print_version ();

  if (strlen(athena_args_purpose) > 0)
    printf("\n%s\n", athena_args_purpose);

  if (strlen(athena_args_usage) > 0)
    printf("\n%s\n", athena_args_usage);

  printf("\n");

  if (strlen(athena_args_description) > 0)
    printf("%s\n\n", athena_args_description);
}

void
arg_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (athena_args_help[i])
    printf("%s\n", athena_args_help[i++]);
}

void
arg_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (athena_args_full_help[i])
    printf("%s\n", athena_args_full_help[i++]);
}

void
arg_parser_init (struct athena_args *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
arg_parser_params_init(struct arg_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct arg_parser_params *
arg_parser_params_create(void)
{
  struct arg_parser_params *params = 
    (struct arg_parser_params *)malloc(sizeof(struct arg_parser_params));
  arg_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
arg_parser_release (struct athena_args *args_info)
{

  free_string_field (&(args_info->base_arg));
  free_string_field (&(args_info->base_orig));
  free_string_field (&(args_info->type_orig));
  free_string_field (&(args_info->out_arg));
  free_string_field (&(args_info->out_orig));
  
  

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
arg_parser_dump(FILE *outfile, struct athena_args *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", ARG_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->base_given)
    write_into_file(outfile, "base", args_info->base_orig, 0);
  if (args_info->download_given)
    write_into_file(outfile, "download", 0, 0 );
  if (args_info->check_given)
    write_into_file(outfile, "check", 0, 0 );
  if (args_info->list_given)
    write_into_file(outfile, "list", 0, 0 );
  if (args_info->type_given)
    write_into_file(outfile, "type", args_info->type_orig, arg_parser_type_values);
  if (args_info->out_given)
    write_into_file(outfile, "out", args_info->out_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
arg_parser_file_save(const char *filename, struct athena_args *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", ARG_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = arg_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
arg_parser_free (struct athena_args *args_info)
{
  arg_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
arg_parser (int argc, char **argv, struct athena_args *args_info)
{
  return arg_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
arg_parser_ext (int argc, char **argv, struct athena_args *args_info,
                   struct arg_parser_params *params)
{
  int result;
  result = arg_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
arg_parser2 (int argc, char **argv, struct athena_args *args_info, int override, int initialize, int check_required)
{
  int result;
  struct arg_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = arg_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
arg_parser_required (struct athena_args *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (arg_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
arg_parser_required2 (struct athena_args *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  
  /* checks for dependences among options */
  if (args_info->download_given && ! args_info->base_given)
    {
      fprintf (stderr, "%s: '--download' ('-d') option depends on option 'base'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->check_given && ! args_info->base_given)
    {
      fprintf (stderr, "%s: '--check' ('-c') option depends on option 'base'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->list_given && ! args_info->base_given)
    {
      fprintf (stderr, "%s: '--list' ('-l') option depends on option 'base'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->type_given && ! args_info->out_given)
    {
      fprintf (stderr, "%s: '--type' ('-t') option depends on option 'out'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }
  if (args_info->out_given && ! args_info->type_given)
    {
      fprintf (stderr, "%s: '--out' ('-o') option depends on option 'type'%s\n", prog_name, (additional_error ? additional_error : ""));
      error = 1;
    }

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see arg_parser_params.check_ambiguity
 * @param override @see arg_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               arg_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_ENUM:
    if (val) *((int *)field) = found;
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };


  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
arg_parser_internal (
  int argc, char **argv, struct athena_args *args_info,
                        struct arg_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct athena_args local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    arg_parser_init (args_info);

  arg_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "base",	2, NULL, 'b' },
        { "download",	0, NULL, 'd' },
        { "check",	0, NULL, 'c' },
        { "list",	0, NULL, 'l' },
        { "type",	1, NULL, 't' },
        { "out",	1, NULL, 'o' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVb::dclt:o:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          arg_parser_print_help ();
          arg_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          arg_parser_print_version ();
          arg_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'b':	/* Use base data..  */
        
        
          if (update_arg( (void *)&(args_info->base_arg), 
               &(args_info->base_orig), &(args_info->base_given),
              &(local_args_info.base_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "base", 'b',
              additional_error))
            goto failure;
        
          break;
        case 'd':	/* Download data.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->download_given),
              &(local_args_info.download_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "download", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Preform consistency check.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->check_given),
              &(local_args_info.check_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "check", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* List file contents.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->list_given),
              &(local_args_info.list_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "list", 'l',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Filetype to output.  */
        
        
          if (update_arg( (void *)&(args_info->type_arg), 
               &(args_info->type_orig), &(args_info->type_given),
              &(local_args_info.type_given), optarg, arg_parser_type_values, 0, ARG_ENUM,
              check_ambiguity, override, 0, 0,
              "type", 't',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output location.  */
        
        
          if (update_arg( (void *)&(args_info->out_arg), 
               &(args_info->out_orig), &(args_info->out_given),
              &(local_args_info.out_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "out", 'o',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            arg_parser_print_full_help ();
            arg_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", ARG_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */



  if (check_required)
    {
      error += arg_parser_required2 (args_info, argv[0], additional_error);
    }

  arg_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  arg_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
